help-link: "If u need help with plugin u can visit wiki https://github.com/SergeyDertan/SRegionProtector/wiki or contact me in telegram https://t.me/sergeydertan"
# default means that plugin will use server`s default language
language: "default"
provider: yaml
#when enabled only /rg and /region commands will be shown
hide-commands: false
#when enabled /rg and /region commands will be executed asyncly
async-commands: true
async-commands-threads: -1

lpos-max-radius: 250

priority-system: false

#multithreaded regions loading
multithreaded-loading: true
multithreaded-loading-threads: -1
# "20", "20:2"
border-block: "20"
#1 second = 20 ticks
select-session-clear-interval: 20
session-life-time: 120
#disabling flags may increase performance
#by default flags are disabled
active-flags:
  place: true
  break: true
  interact: true
  use: true
  pvp: true
  explode: true
  lighter: true
  magic-item-use: false
  heal: false
  invincible: true
  potion-launch: true
  move: false
  leaves_decay: false
  item_drop: false
  send_chat: false
  receive_chat: false
  health_regen: false
  mob-damage: false
  mob-spawn: false
  crops-destroy: true
  redstone: false
  ender-pearl: false
  explode-block-break: true
  liquid-flow: true
  lightning-strike: true
  fire: true
  chest-access: true
  sleep: true
  chunk-loader: false
  smart-doors: true
  minefarm: true
display:
  place: true
  break: true
  interact: true
  use: true
  pvp: true
  explode: true
  lighter: true
  magic-item-use: true
  heal: true
  invincible: true
  potion-launch: true
  move: true
  leaves_decay: true
  item_drop: true
  send_chat: true
  receive_chat: true
  health_regen: true
  mob-damage: true
  mob-spawn: true
  crops-destroy: true
  redstone: true
  ender-pearl: true
  explode-block-break: true
  liquid-flow: true
  lightning-strike: true
  fire: true
  chest-access: true
  sleep: true
  chunk-loader: true
  smart-doors: true
  minefarm: true
# permissions will be created during the plugin loading and have names sregionprotector.region.size.MAX_REGION_SIZE
# for example, if you have
# region-sizes:
#  - 10
#  - 20
# 2 permissions will be created: sregionprotector.region.size.10 and sregionprotector.region.size.20
region-sizes:
  - 1000
  - 10000
  - 20000
# permissions will be created during the plugin loading and have names sregionprotector.region.amount.MAX_REGION_AMOUNT
# for example, if you have
# region-amounts:
#  - 1
#  - 2
# 2 permissions will be created: sregionprotector.region.amount.1 and sregionprotector.region.amount.20
region-amounts:
  - 1
  - 2
  - 3
#in seconds
auto-save-period: 60
