default-flags:
  move: false
  build: true
  interact: false
  use: true
  pvp: true
  explode: true
  lighter: true
  magic-item-use: false
  heal: false
  invincible: false
  potion-launch: false
  leaves-decay: false
  item_drop: false
  send_chat: false
  receive_chat: false
  health_regen: false
  mob-damage: false
  mob-spawn: false
#
need-message:
  move: false
  build: true
  interact: true
  use: true
  pvp: true
  explode: false
  lighter: false
  magic-item-use: false
  heal: false
  invincible: false
  potion-launch: false
  leaves-decay: false
  item_drop: true
  send_chat: true
  receive_chat: false
  health_regen: false
  mob-damage: false
  mob-spawn: false
max-region-name-length: 10
min-region-name-length: 3
# 1 second = 20 ticks
heal-flag-heal-delay: 40
heal-flag-heal-amount: 3