default-flags:
  move: false
  build: true
  interact: false
  use: true
  pvp: true
  explode: true
  lighter: true
  magic-item-use: false
  heal: false
  invincible: false
  potion-launch: false
  leaves-decay: false
  item_drop: false
  send_chat: false
  receive_chat: false
  health_regen: false
max-region-name-length: 10
min-region-name-length: 3